version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg-ibaurora
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ibaurora
    networks:
      - appworks
  
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq-ibaurora
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=docker
      - RABBITMQ_DEFAULT_VHOST=/
networks:
  appworks:
    driver: bridge